# Log rotation for smbmounter, installed to /etc/newsyslog.d/com.brian.smbmounter.conf
# logfilename               [owner:group]  mode count size  when  flags
/var/log/smbmounter.log      root:wheel     644   7     1000  *     J
/var/log/smbmounter.err      root:wheel     644   7     1000  *     J
